name: GitHub Stats Bot

on:
  # 只要你保存了这个文件，脚本就会立刻被揪起来执行一次！
  push:
    branches: [ master ] 
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: 

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch and Save GitHub Stats
        uses: jasonetco/github-stats-action@v2
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
