name: GitHub Stats Bot

on:
  push:
    branches: [ master ] # 保存时立刻跑一次测试
  schedule:
    - cron: '0 12 * * *'  # 每天北京时间晚上 8 点自动运行
  workflow_dispatch:      # 允许手动点击按钮触发

# 赋予脚本自动创建 gh-pages 分支和发布网页的权限
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch and Save GitHub Stats
        # 这里改成了官方标准推荐的 @v1 动态版本
        uses: jgehrcke/github-repo-stats@v1
        with:
          repository: ${{ github.repository }}
          ghtoken: ${{ secrets.GH_TOKEN }}
